package aps.unip.enums;

public enum Status {
	STATUS_OK,
	STATUS_ERRO_PARAMETRO,
	STATUS_ERRO_SERVIDOR,
	STATUS_ERRO_CLIENTE,
	STATUS_ERRO_CADASTRO,
	STATUS_ERRO_LOGIN,
	NOVA_MENSAGEM,
	VALIDADO,
	USUARIO_NAO_CADASTRADO,
	CADASTRO_EFETUADO,
	CADASTRO_NAO_EFETUADO,
	MENSAGEM_ENVIADA,
	MENSAGEM_NAO_ENVIADA,
	MENSAGEM_ARQUIVADA,
	USUARIOS_ENCONTRADOS,
	NENHUM_USUARIO_ENCONTRADO
}
