package aps.unip.enums;

public enum Status {
	STATUS_OK,
	STATUS_ERRO_PARAMETRO,
	STATUS_ERRO_SERVIDOR,
	STATUS_ERRO_CLIENTE,
	STATUS_ERRO_CADASTRO,
	STATUS_ERRO_LOGIN,
	NOVA_MENSAGEM,
	VALIDADO,
	USUARIO_NAO_CADASTRADO
}
